#设置注册中心的地址： http://localhost:8761/eureka/ , 与 eureka-server 中的配置 application.yml 遥相呼应
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: trend-trading-backtest-service

feign.hystrix.enabled: true

zipkin:
  base-url: http://localhost:9411

# 增加如下内容，才可以访问
# actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
